// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlyyvkcqtpzllzkllypi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseXl2a2NxdHB6bGx6a2xseXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTk5MDYsImV4cCI6MjA2ODUzNTkwNn0.E8pHR7CT6QbC4dHP7CDk671Kaz6Qkc6Pqf55oCKmJvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});